// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ForwardRule {
  id: string
  sourceHost: string
  localPort: number
  targetHost: string
  targetPort: number
  enabled: boolean
  createdAt: string
}

export interface LogEntry {
  timestamp: string
  source: string
  bytesIn: number
  bytesOut: number
  status: string
}

export interface WebUIConfig {
  enabled: boolean
  port: number
  password: string
}

export function AddRule(arg1: string, arg2: number, arg3: string, arg4: number): Promise<void>;
export function ClearLogs(arg1: string): Promise<void>;
export function DeleteRule(arg1: string): Promise<void>;
export function GetLogs(arg1: string, arg2: number): Promise<LogEntry[]>;
export function GetRules(): Promise<ForwardRule[]>;
export function GetStatus(): Promise<{ [key: string]: boolean }>;
export function GetWebUIConfig(): Promise<WebUIConfig>;
export function ToggleRule(arg1: string, arg2: boolean): Promise<void>;
export function UpdateWebUIConfig(arg1: boolean, arg2: number, arg3: string): Promise<void>;
